
services:
  # NestJS 后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus-law-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - nexus_net

  # React 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus-law-frontend
    restart: always
    ports:
      - "80:80"  # 暴露给外网的 80 端口 (HTTP)
    depends_on:
      - backend
    networks:
      - nexus_net

# 定义共享网络
networks:
  nexus_net:
    driver: bridge